initStore([
  {
    id: 0,
    title: 'Horizon Forbidden West (PS5/PS4)',
    description: 'Explore a lush post-apocalyptic world filled with robotic creatures.',
    price: 69.95,
    discountPrice: 59.95,
    image: 'assets/images/service-1.jpg',
  },
  {
    id: 1,
    title: 'God of War Ragnarök (PS5/PS4)',
    description: 'Join Kratos and Atreus in an epic Norse mythology adventure.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'assets/images/service-2.jpg',
  },
  {
    id: 2,
    title: 'Forza Horizon 5 (Xbox/PC)',
    description: 'Race across a stunning open-world version of Mexico with hundreds of cars.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'assets/images/service-3.jpg',
  },
  {
    id: 3,
    title: 'Elden Ring (PC/PS5/Xbox)',
    description: 'Venture through a vast fantasy world with challenging enemies and deep lore.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'assets/images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Resident Evil 4 Remake (PC/PS5/Xbox)',
    description: 'Experience the classic horror game fully rebuilt for modern consoles.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'assets/images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Mario Kart 8 Deluxe (Switch)',
    description: 'Enjoy fast-paced, fun kart racing with iconic Nintendo characters.',
    price: 49.95,
    discountPrice: 39.95,
    image: 'assets/images/service-6.jpg',
  },
]);