initStore([
  {
    id: 0,
    title: 'Elden Ring (PC/PS5/Xbox)',
    description: 'Venture through a vast fantasy world with challenging enemies and deep lore.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'assets/images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Forza Horizon 5 (Xbox/PC)',
    description: 'Race across a stunning open-world version of Mexico with hundreds of cars.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'assets/images/service-2.jpg',
  },
  {
    id: 2,
    title: 'Resident Evil 4 Remake (PC/PS5/Xbox)',
    description: 'Experience the classic horror game fully rebuilt for modern consoles and PC.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'assets/images/service-3.jpg',
  },
  {
    id: 3,
    title: 'Cyberpunk 2077 (PC/PS5/Xbox)',
    description: 'Dive into a dystopian future with open-world exploration and rich storylines.',
    price: 49.95,
    discountPrice: 39.95,
    image: 'assets/images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Call of Duty: Modern Warfare II (PC/PS5/Xbox)',
    description: 'Experience high-intensity action and tactical multiplayer combat.',
    price: 69.95,
    discountPrice: 59.95,
    image: 'assets/images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Death Stranding Director’s Cut (PC/PS5)',
    description: 'Explore a post-apocalyptic America with innovative gameplay and story.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'assets/images/service-6.jpg',
  },
]);
